name: Conditionals

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
        #step 1 : only runs on main branch
      - name: Run only on main
        if: github.ref == 'refs/heads/main'
        run: echo "This runs only on main branch"

        #step 2: step that fails
      - name: Intentional failure
        run: exit 1
        #step 3: runs only if previous step failed
      - name: Run if previous failed
        if: failure()
        run: echo "Previous step failed, so this runs"
# Step 4: Continue on error
      - name: Continue on error
        run: exit 1
        continue-on-error: true
 # This step will fail but workflow continues