name: External Trigger

on:
  repository_dispatch:
    types: [deploy-request]

jobs:
  external:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment from payload
        run: 'echo "Triggered by external system, environment: ${{ github.event.client_payload.environment }}"'