name: scheduled Workflow

on:
  workflow_dispatch:

jobs:
  daily-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Schedule run
        run: echo "Scheduled workflow running at midnight that is 00:00"
