name: Secret Environment Variable

on:
  workflow_dispatch

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Secrets as environment varaibles
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "Logging in with Docker username: $DOCKER_USERNAME"
          echo "Token length: ${#Docker_TOKEN}"