name: smart pipeline

on:
  workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint code
        run: echo "Running lint checks...."
        
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Runs Tests
        run: echo "Running tests...."

  summary: 
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Print branch type
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "This is a main branch push"
          else
            echo "This is a feature branch push"
          fi
          echo "Commit message: ${{ github.event.commits[0].message }}"