name: Smart Triggers

on:
  push:
    branches:
      - main
      - release/*
    paths:
      - 'src/**'
      - 'app/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered because src/ or app/ changed"